openapi: 3.0.0
paths:
  "/v1/claim-free-share/{userId}":
    post:
      operationId: RewardController_claimFreeShare
      parameters:
        - name: userId
          required: true
          in: path
          schema:
            type: string
      responses:
        "201":
          description: ""
      tags:
        - v1
info:
  title: Reward Service API
  description: Reward Service API documentation
  version: Emma
  contact: {}
tags:
  - name: Reward Service
    description: ""
servers: []
components:
  schemas: {}
